import Navbar from "@/components/Navbar"

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div className="relative flex min-h-screen flex-col">
			<Navbar />
			<main className="flex-1">{children}</main>
		</div>
	)
}
