import { currentUser } from "@clerk/nextjs"

import { SiteFooter } from "@/components/layouts/site-footer"
import { SiteHeader } from "@/components/layouts/site-header"

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const user = await currentUser()

	return (
		<div className="relative flex min-h-screen flex-col">
			{/* <Navbar /> */}
			<SiteHeader user={user} />
			<main className="flex-1">{children}</main>
			<SiteFooter />
		</div>
	)
}
