name: Enable auto merge PR

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  pull-requests: write
  contents: write

jobs:
  Enable_auto_merge_pr:
    runs-on: ubuntu-latest
    if: ! github.event.pull_request.draft
    steps:
      # Finally, this sets the PR to allow auto-merging for patch and minor
      # updates if all checks pass
      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
